spring:
  application:
    name: demo
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgre
  schema-generation:
    create-schema: true
    mode: create
transactional:
  enabled: true